[package]
name = "lattice-node"
version.workspace = true
edition.workspace = true
description = "Neon bindings for embedding Lattice in Node.js"
license.workspace = true

[lib]
name = "lattice_node"
crate-type = ["cdylib"]

[dependencies]
lattice = { path = "../lattice", default-features = false }
neon = "1"

[features]
default = []
sql = ["lattice/sql"]
